version: '3.9'
services:

  #PHP Service
  app:
    image: ghcr.io/codis-ru/docker:latest
    ports:
      - "127.0.0.1:9000:9000"
    # seems like fpm receives the full path from nginx
    # and tries to find the files in this dock, so it must
    # be the same as nginx.root
    volumes:
      - /web/hram.codis.ru/docs:/var/www/html/hram.codis.ru:ro
      - /web/docker/etc/php/php.ini:/usr/local/etc/php/php.ini:ro
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    volumes:
      - /web/docker/etc/nginx/hram.conf:/etc/nginx/conf.d/hram.conf:ro
      - /web/hram.codis.ru/docs:/var/www/html/hram.codis.ru:ro
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - /web/mysql-dump/hram.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
